@startuml
title Collaboration Diagram: Booking Process

skinparam style strictuml
skinparam linetype polyline

actor "Passenger" as P
rectangle "CarConnect System" as Sys
actor "Driver" as D

' Triangle Layout links
P -down- Sys
Sys -right- D

' Messages Passenger <-> System
P -[#black]> Sys : 1: Request Booking >
Sys -[#black]> P : 4: Confirm Booking >

' Messages System <-> Driver
Sys -[#black]> D : 2: Notify Request >
D -[#black]> Sys : 3: Accept Request >

@enduml
